"""The Python decoder and timing must reproduce the deployed JavaScript exactly.

Reference: tests/fixtures/js_reference_decode.json, generated by running the
original Apps Script functions on every message in the RockBLOCK export
(see build_js_reference.py).
"""
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

from powometer.decoders.powometer_payload import parse_payload
from powometer.timing import (CLOCK_TRUST_MIN, QUEUE_INTERVAL, clock_offset_minutes,
                              measurement_times)

FIX = Path(__file__).parent / "fixtures" / "js_reference_decode.json"
REF = json.loads(FIX.read_text())


def utc(s):
    return datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)


def test_fixture_covers_the_whole_export():
    assert len(REF) == 2587
    assert sum(1 for r in REF if r["js"]) == 2509


@pytest.mark.parametrize("i", range(len(REF)))
def test_matches_javascript(i):
    r = REF[i]
    p = parse_payload(r["payload"])
    js = r["js"]
    if js is None:
        assert p is None
        return
    assert p is not None
    jp = js["p"]
    assert (p.day, p.hour, p.minute, p.battery_bucket) == (jp["day"], jp["hour"], jp["minute"], jp["batteryLevel"])
    assert len(p.readings) == len(jp["readings"])
    for mine, theirs in zip(p.readings, jp["readings"]):
        if theirs is None:
            assert mine is None
            continue
        d = None if mine.distance_cm is None else mine.distance_cm / 100
        assert d == theirs["distance"]
        assert mine.air_temperature_c == theirs["temperature"]
        assert mine.relative_humidity_pct == theirs["humidity"]
    t = utc(r["transmit_utc"])
    off = clock_offset_minutes(p, t)
    assert (off if off is not None else "") == js["off"]
    times, source = measurement_times(p, t)
    assert source == js["source"]
    assert [int(x.timestamp() * 1000) for x in times] == js["times"]


# --- behaviour checks (from the 2026-09-29 Apps Script tests) --------------

TX = datetime(2026, 9, 28, 14, 33, 25, tzinfo=timezone.utc)
FIRST = TX - 4 * QUEUE_INTERVAL          # 5-reading bundle


def bundle(first_wall: datetime) -> str:
    return first_wall.strftime("%d%H%M") + "3" + ":".join(["381+01595"] * 5)


@pytest.mark.parametrize("shift_min,expected", [
    (29, "station time"), (-29, "station time"),
    (31, "transmit time (station clock off by 31 min)"),
    (-31, "transmit time (station clock off by -31 min)"),
])
def test_trust_window(shift_min, expected):
    wall = FIRST - timedelta(hours=8) + timedelta(minutes=shift_min)
    _, source = measurement_times(parse_payload(bundle(wall)), TX)
    assert source == expected
    assert CLOCK_TRUST_MIN == 30


@pytest.mark.parametrize("header", ["000207", "282607"])
def test_unreadable_header_falls_back(header):
    _, source = measurement_times(parse_payload(header + "3" + "381+01595"), TX)
    assert source == "transmit time (station clock unreadable)"


def test_dead_station_clock_falls_back():
    # RTC at its 2000-01-01 default -> header "010000"
    _, source = measurement_times(parse_payload("0100003" + "381+01595:382+01595"), TX)
    assert source.startswith("transmit time (station clock off by")


def test_month_boundary():
    tx = datetime(2026, 10, 1, 12, 25, tzinfo=timezone.utc)
    times, source = measurement_times(parse_payload("3023553" + ":".join(["381+01595"] * 5)), tx)
    assert source == "station time"
    assert times[0] == datetime(2026, 10, 1, 7, 55, tzinfo=timezone.utc)   # 30 Sep 23:55 UTC-8


def test_sentinels():
    p = parse_payload("2812055" + "499-99900:498+01000:500+01000:394+06194")
    a, b, c, d = p.readings
    assert a.distance_cm is None and a.air_temperature_c is None and a.relative_humidity_pct is None
    assert b.distance_cm is None and b.relative_humidity_pct == 100
    assert c.distance_cm is None
    assert (d.distance_cm, d.air_temperature_c, d.relative_humidity_pct) == (394, 6.1, 94)


def test_malformed_reading_keeps_slot():
    p = parse_payload("2812055" + "394+06194:XXXXXXXXX:395+06194")
    assert p.readings[1] is None and p.readings[2].distance_cm == 395


@pytest.mark.parametrize("text", ["Hello World", "103", "2024,4,19,19,16,44,22.23,1013.70", ""])
def test_non_station_payloads(text):
    assert parse_payload(text) is None
